src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $video;

    #[ORM\Column(type: 'text')]
    private $synopsis;

    #[ORM\Column(type: 'datetime')]
    private $published_at;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    private $user;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Reviews::class)]
    private $reviews;

    #[ORM\Column(type: 'datetime')]
    private $released_at;

    #[ORM\Column(type: 'array')]
    private $categories = [];

    #[ORM\Column(type: 'string', length: 80)]
    private $director;

    #[ORM\Column(type: 'string', length: 150)]
    private $actors;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'favposts')]
    private $favorites;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comments::class)]
    private $comments;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->favoris = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Reviews[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setPost($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getPost() === $this) {
                $review->setPost(null);
            }
        }

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeInterface
    {
        return $this->released_at;
    }

    public function setReleasedAt(\DateTimeInterface $released_at): self
    {
        $this->released_at = $released_at;

        return $this;
    }

    public function getCategories(): ?array
    {
        return $this->categories;
    }

    public function setCategories(array $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getActors(): ?string
    {
        return $this->actors;
    }

    public function setActors(string $actors): self
    {
        $this->actors = $actors;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(User $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
        }

        return $this;
    }

    public function removeFavorite(User $favorite): self
    {
        $this->favorites->removeElement($favorite);

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comments;
use App\Entity\Post;
use App\Entity\Reviews;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[IsGranted("ROLE_USER")]
class PostController extends AbstractController
{

    private $managerRegistry; // Stockera l'accès a la base de données


    /******************************************
     * /!\ Mes catégories de film, 
     * si modification, la reporter sur la bdd
     ******************************************/
    public $categories = [
        'Thriller'          => 'Thriller',
        'Comédie'           => 'Comédie',
        'SF'                => 'SF',
        'Drame'             => 'Drame',
        'Animation'         => 'Animation',
        'Horreur'           => 'Horreur',
        'Romance'           => 'Romance',
        'Aventure'          => 'Aventure',
        'Action'            => 'Action',
        'Fantastique'       => 'Fantastique',
        'Documentaire'      => 'Documentaire',
    ];



    public function __construct(ManagerRegistry $managerRegistry)
    {
        $this->managerRegistry = $managerRegistry; // Applique l'accès a la base de données
    }

    #[Route('/list', name: 'posts')]
    public function list(): Response
    {
        $em = $this->managerRegistry->getManager();

        $posts = $em->getRepository(Post::class)->findBy([], ['published_at' => 'DESC']);

        return $this->render('post/list.html.twig', [
            'posts' => $posts,
            'categories' => $this->categories
        ]);
    }

    #[Route('/analyse', name: 'analyse')]
    public function analyse(): Response
    {
        

        return $this->render('analyse.html.twig');
            
        
    }


    #[Route('/ruche', name: 'ruche')]
    public function ruche(): Response
    {
        

        return $this->render('ruche.html.twig');
            
        
    }


    #[Route('/details-de-post/{id}', name: 'post_view')]
    public function view(int $id): Response
    {
        $em = $this->managerRegistry->getManager();

        $post = $em->getRepository(Post::class)->find($id);

        $reviews = $post->getReviews();

        $comments = $post->getComments();

        $favposts = $this->getUser()->getFavposts();
        
        $currentUser = $this->getUser();

        if (empty($post)) {
            throw new NotFoundHttpException('Film/série introuvable');
        }

        return $this->render('post/view.html.twig', [
            'post' => $post,
            'reviews' => $reviews,
            'comments' => $comments,
            'favposts' => $favposts,
            'currentUser' => $currentUser
        ]);
    }

    /**
     * Ajouter un post
     */

    #[Route('/ajouter-un-post', name: 'post_add')]
    // #[IsGranted("ROLE_ADMIN")]
    public function add(): Response
    {
        $errors = [];

        if (!empty($_POST)) {


            // On nettoies les données en cas de champs à choix multiple (catégorie ici)
            foreach ($_POST as $key => $value) {
                if (is_array($value)) {
                    $safe[$key] = array_map('trim', array_map('strip_tags', $value));
                } else {
                    $safe[$key] = trim(strip_tags($value));
                }
            }
            

            if (strlen($safe['title']) < 1 || strlen($safe['title']) > 100) {
                $errors[] = 'Votre titre doit comporter entre 1 et 100 caractères';
            }
            if (strlen($safe['synopsis']) < 10 || strlen($safe['synopsis']) > 5000) {
                $errors[] = 'Votre synopsis doit comporter entre 10 et 5000 caractères';
            }

            if (strlen($safe['director']) < 5 || strlen($safe['director']) > 80) {
                $errors[] = 'Le nom de réalisateur doit comporter entre 5 et 80 caractères';
            }

            if (strlen($safe['actors']) < 5 || strlen($safe['actors']) > 100) {
                $errors[] = 'Les noms des acteurs doivent comporter entre 5 et 100 caractères';
            }

            if (!empty($safe['released_at'])) {
                $date_release = explode('-', $safe['released_at']);
                if (!checkdate($date_release[1], $date_release[2], $date_release[0])) {
                    $errors[] = 'La date de sortie est invalide';
                }
            } else {
                $errors[] = 'La date de sortie est obligatoire';
            }


            if (!empty($_FILES) && $_FILES['image']['error'] == 0) {

                $to = $_SERVER['DOCUMENT_ROOT'] . '/uploads/covers/';
                $tmp_name = $_FILES["image"]["tmp_name"];
                $name = basename($_FILES["image"]["name"]);
                move_uploaded_file($tmp_name, "$to/$name");
            }

            if (count($errors) === 0) {
                $em = $this->managerRegistry->getManager();

                $post = new Post();
                $post->setTitle($safe['title']);
                $post->setSynopsis($safe['synopsis']);
                $post->setUser($this->getUser());
                $post->setDirector($safe['director']);
                $post->setActors($safe['actors']);
                $post->setImage($name);
                $post->setVideo($safe['video']);
                $post->setCategories($safe['category']);
                $post->setReleasedAt(new \DateTime($safe['released_at']));
                $post->setPublishedAt(new \DateTime('now')); // Applique une datetime à l'instant T


                $em->persist($post);
                $em->flush();

                $this->addFlash('success', 'Votre post a bien été enregistrée');
            } else {
                $this->addFlash('errors', implode('<br>', $errors));
            }
        }

        return $this->render('post/add.html.twig', [
            'categories' => $this->categories
        ]);
    }

    /**
     * Modifier un post
     */
    #[IsGranted("ROLE_ADMIN")]
    #[Route('/modifier-un-post/{id}', name: 'post_edit')]
    public function edit(int $id): Response
    {
        $errors = [];

        $em = $this->managerRegistry->getManager();

        $post = $em->getRepository(Post::class)->find($id); // Permet de récupérer le post donné en id        

        if (!empty($_POST)) {


            // On nettoies les données en cas de champs à choix multiple (catégorie ici)
            foreach ($_POST as $key => $value) {
                if (is_array($value)) {
                    $safe[$key] = array_map('trim', array_map('strip_tags', $value));
                } else {
                    $safe[$key] = trim(strip_tags($value));
                }
            }


            if (strlen($safe['title']) < 4 || strlen($safe['title']) > 100) {
                $errors[] = 'Votre titre doit comporter entre 4 et 100 caractères';
            }
            if (strlen($safe['synopsis']) < 10 || strlen($safe['synopsis']) > 5000) {
                $errors[] = 'Votre synopsis doit comporter entre 10 et 5000 caractères';
            }

            if (strlen($safe['director']) < 5 || strlen($safe['director']) > 80) {
                $errors[] = 'Le nom de réalisateur doit comporter entre 5 et 80 caractères';
            }

            if (strlen($safe['actors']) < 5 || strlen($safe['actors']) > 100) {
                $errors[] = 'Les noms des acteurs doivent comporter entre 5 et 100 caractères';
            }

            if (!empty($safe['released_at'])) {
                $date_release = explode('-', $safe['released_at']);
                if (!checkdate($date_release[1], $date_release[2], $date_release[0])) {
                    $errors[] = 'La date de sortie est invalide';
                }
            } else {
                $errors[] = 'La date de sortie est obligatoire';
            }

            if (!empty($_FILES['image']['tmp_name'])) {
                if ($_FILES['image']['error'] == 4) {
                    $errors[] = 'Ajouter une affiche du film (jpg, jpeg, png)';
                } else{
                    $to = $_SERVER['DOCUMENT_ROOT'] . '/uploads/';
                    $tmp_name = $_FILES["image"]["tmp_name"];
                    $name = basename($_FILES["image"]["name"]);
                    move_uploaded_file($tmp_name, "$to/$name");
                }
            }else{
                $name = $post->getImage();
            }


            if (!isset($safe['category'])) {
                $errors[] = 'Veuillez sélectionner une catégorie';
            } /*elseif (!in_array($safe[$key], array_keys($this->categories))) {
                $errors[] = 'Votre catégorie sélectionnée n\'existe pas';
            }*/


            if (count($errors) === 0) {
                $em = $this->managerRegistry->getManager();

                $post->setTitle($safe['title']);
                $post->setSynopsis($safe['synopsis']);
                $post->setUser($this->getUser());
                $post->setDirector($safe['director']);
                $post->setActors($safe['actors']);
                $post->setImage($name);
                $post->setVideo($safe['video']);
                $post->setCategories($safe['category']);
                $post->setReleasedAt(new \DateTime($safe['released_at']));
                $post->setPublishedAt(new \DateTime('now')); // Applique une datetime à l'instant T


                $em->persist($post);
                $em->flush();

                $this->addFlash('success', 'Votre post a bien été modifiée');
            } else {
                $this->addFlash('errors', implode('<br>', $errors));
            }
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'categories' => $this->categories

templates/post/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un post{% endblock %}

{% block body %}

<h1 class="text-center mt-4">Ajouter un post</h1>

<form method="post" enctype="multipart/form-data" class="fs-5">
        <div class="mb-3">
            <label for="title">Titre du film</label>
            <input type="text" name="title" id="title" class="form-control">
        </div>

        <div class="mb-3">
            <label for="synopsis">Synopsis</label>
            <textarea name="synopsis" id="synopsis" rows="6" class="form-control"></textarea>
        </div>

        <div class="mb-3">
            <label for="director">Réalisateur</label>
            <input type="text" name="director" id="director" class="form-control">
        </div>

        <div class="mb-3">
            <label for="actors">Acteurs</label>
            <input type="text" name="actors" id="actors" rows="4" class="form-control">
        </div>

        <div class="mb-3">
			<label for="released_at" class="form-label">Date de sortie</label>
			<input type="date" name="released_at" id="released_at" class="form-control">
		</div>

        <div class="mb-3">
			<label for="image" class="form-label">Affiche du film</label>
			<input type="file" name="image" id="image" class="form-control" accept="image/png, image/jpeg, image/jpg, image/gif, image/webp">
		</div>

        <div class="mb-3">
            <label for="video">Vidéo</label>
            <input type="text" name="video" id="video" placeholder="Mettez un lien url valide" class="form-control">
        </div>


        <div class="mb-3">
            <label for="category" class="form-label">Catégorie</label>
            {% for category in categories %}
            <label>
                <input type="checkbox" name="category[]" value="{{category}}">{{ category }}
            </label>
            {% endfor %}
        </div>

        <button class="btn btn-primary mt-3 mb-3" type="submit">Enregistrer</button>
    </form>

{% endblock %}

templates/post/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un post{% endblock %}

{% block body %}

    <form>
        <h3>Supprimer {{ post.title }} ?</h3>
        <button class="btn btn-primary" type="submit" name="submit">Oui</button>
        <a class="btn btn-dark" href="{{ path('post_view', {id: post.id}) }}">Annuler</a>
    </form>

{% endblock %}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/post/edit.css')}}">
{% endblock %}

{% block title %}Modifier un post{% endblock %}

{% block body %}
<form method="post" >
    <div class="container w-75 mt-4 fs-5 mb-4">
        <h1 class="mb-4">Modifier la page film "{{ post.title }}"</h1>
        <div class="mb-3">
            <label for="title">Titre du film</label>
            <input type="text" name="title" id="title" class="form-control" value="{{ post.title }}">
        </div>

        <div class="mb-3">
            <label for="synopsis">Synopsis</label>
            <textarea name="synopsis" id="synopsis" rows="6" class="form-control" value="{{ post.synopsis }}">{{ post.synopsis }}</textarea>
        </div>

        <div class="mb-3">
            <label for="director">Réalisateur</label>
            <input type="text" name="director" id="director" class="form-control" value="{{ post.director }}">
        </div>

        <div class="mb-3">
            <label for="actors">Acteurs</label>
            <input type="text" name="actors" id="actors" rows="4" class="form-control" value="{{ post.actors }}">
        </div>

        <div class="mb-3">
			<label for="released_at" class="form-label">Date de sortie</label>
			<input type="date" name="released_at" id="released_at" class="form-control" value="{{ post.releasedAt|date('Y-m-d') }}">
		</div>

        <div class="mb-3">
			<label for="image" class="form-label">Affiche du film</label>
			<input type="file" name="image" id="image" class="form-control" accept="image/*" value="{{ post.image }}">
		</div>

        <div class="mb-3">
            <label for="video">Vidéo</label>
            <input type="text" name="video" id="video" placeholder="Mettez un lien url valide" class="form-control" value="{{ post.video }}">
        </div>

        <div class="mb-3">
            <label for="category" class="form-label">Catégories</label>
            {% for category in categories %}
            <label>
                <input type="checkbox" name="category[]" value="{{category}}" {{ (category in post.categories) ? 'checked' : '' }}> {{ category }}
            </label>
            {% endfor %}
        </div>

        <button class="save_button btn btn-primary mb-3" type="submit">Enregistrer les modifications</button>

        <a class="back_button btn btn-primary mb-3" href="{{ path('post_view', {id: post.id}) }}">Revenir sur la publication</a>
    </div>
</form>

{% endblock %}

templates/post/view.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/post/view.css')}}">
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block body %}

<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .review { display: none; }
    .comment { display: none; }
    .commentsList { display: none; }
</style>

    <div class="container-sm mt-5">
        <div class="row block align-items-center">
            <div class="col-sm-5">
                {% if post.image is not empty  %}
                <img class="img-fluid cover" src="{{ asset('uploads/covers/' ~ post.image) }}" alt="affiche">
                {% endif %}
            </div>
            <div class="col-infos col-sm-7 mt-3">
                <h1 class="title text-center">{{ post.title }} </h1>
                
                

                {% if post.synopsis|length < 270 %}
                    <p class="synopsis_short">{{ post.synopsis|nl2br }}</p>
                {% elseif post.synopsis|length > 270 and post.synopsis|length < 430 %}
                    <p class="synopsis_medium">{{ post.synopsis|nl2br }}</p>
                {% elseif post.synopsis|length > 430 and post.synopsis|length < 700 %}
                    <p class="synopsis_long">{{ post.synopsis|nl2br }}</p>
                {% endif %}

                <div class="buttons mt-5">
                    <a href="#reviewList" class="add_review btn btn-outline-dark mb-3 me-2 fs-5 scroll-link" id="seeReviews">Voir les commentaires</a>
                    <a href="#add_review" class="add_review btn btn-outline-dark mb-3 me-2 fs-5 scroll-link" id="addReview">Ajouter un commentaire</a>
                </div>
                   

                {% if is_granted('ROLE_ADMIN') %}
                    <div class="admin_buttons">
                        <a class="post_admin btn btn-outline-dark mb-3" href="{{ path('post_edit', {'id':post.id}) }}">Modifier ce post</a>
                        <a class="post_admin btn btn-outline-dark mb-3" href="{{ path('post_delete', {'id':post.id}) }}">Supprimer ce post</a>
                    </div>
                {% endif %}
            </div>
        </div>
        
    </div>
    <div class="review" id="add_review">
        {% include "reviews/add.html.twig" %}
    </div>
    <div id="reviewList" class="container-lg reviews mt-5 w-75">
        {% for review in reviews|reverse %}
            <div class="seereview row align-items-center">
                <div class="form-control mb-3">
                    <p class="user text-muted">Commentaire de 
                        <a href="{{ path('user_profile', {'id':review.user.id}) }}" style="text-decoration: none;">{{ review.user.username }} 
                            {# <img src="{{ asset( 'uploads/profilePicture/' ~ review.user.profilePicture) }}" alt="profile picture user" style="width:50px;"> #}
                        </a>
                    </p>
                    <p class="fs-5 mb-1">{{ review.title }}</p>
                    
                    {% if review.note == 1 %}
                        <i class="fas fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                    {% endif %}
                    {% if review.note == 2 %}
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                    {% endif %}
                    {% if review.note == 3 %}
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                    {% endif %}
                    {% if review.note == 4 %}
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="far fa-star  text-warning"></i>
                    {% endif %}
                    {% if review.note == 5 %}
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                        <i class="fas fa-star  text-warning"></i>
                    {% endif %}

                    <p class="mt-1">{{ review.content|nl2br }}</p>
                    <p>
                        <small class="text-muted">Le </small>{{ review.publishedAt|date('d/m/Y') }}
                        <small class="text-muted"> à </small>{{ review.publishedAt|date('H:i') }}
                    </p>

                    <button class="see_comments btn btn-primary me-2">Voir les réponses</button>
                    <button class="addComment btn btn-outline-dark">Répondre à {{ review.user.username }}</button>

                    <div class="comment mt-3">
                        {% include "comments/add.html.twig" %}
                    </div>
                    <div class="form-control commentsList mt-2 w-75 border-0">
                        {% for comment in comments|reverse %}
                        {% if review.id == comment.review.id %}
                            <hr>
                            <p class="mb-2">
                                <small class="text-muted">Réponse de </small>
                                <a href="{{ path('user_profile', {'id':review.user.id}) }}" style="text-decoration: none;">{{ comment.user.username }}</a>
                                <small class="text-muted"> le </small>{{ comment.publishedAt|date('d/m/Y') }}
                                <small class="text-muted"> à </small>{{ comment.publishedAt|date('H:i') }}
                            </p>
                            <p class="mb-3">{{ comment.content}}<p>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    
    {% block javascripts %}
        <script>

            /* const seeReviews = document.getElementById("seeReviews");
            const reviews = document.getElementsByClassName("reviews");
            
            seeReviews.onclick = function () {
                if (reviews[0].style.display !== "block") {
                    reviews[0].style.display = "block";
                } else {
                    reviews[0].style.display = "none";
                }
                review[0].style.display = "none";
            }; */

            const addReview = document.getElementById("addReview");
            const review = document.getElementsByClassName("review");
            
            addReview.onclick = function () {
                if (review[0].style.display !== "block") {
                    review[0].style.display = "block";
                } else {
                    review[0].style.display = "none";
                }
                reviews[0].style.display = "none";
            };

            const addComment = document.getElementsByClassName("addComment");
            const comment = document.getElementsByClassName("comment");

            for(let i=0; i<2; i++){
                addComment[i].onclick = function () {
                    if (comment[i].style.display !== "block") {
                        comment[i].style.display = "block";
                    } else {
                        comment[i].style.display = "none";
                    }
                    addComment.style.display ='none'
                };
            };

            
            const see_comments = document.getElementsByClassName("see_comments");
            const commentsList = document.getElementsByClassName("commentsList");
            
            for(let i=0; i<5; i++){
                see_comments[i].onclick = function () {
                    if (commentsList[i].style.display !== "block") {
                        commentsList[i].style.display = "block";
                    } else {
                        commentsList[i].style.display = "none";
                    }
                };
            };
        

            $('.scroll-link').click(function(e) {
                e.preventDefault();
                var anchor = $(this.hash);
                $('html, body').animate({ 
                    scrollTop: anchor.offset().top 
                }, 1250);
            });

        </script>
    {% endblock %}
{% endblock %}