src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 80)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 80)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 80)]
    private $username;

    #[ORM\Column(type: 'string', length: 255)]
    private $gender;

    #[ORM\Column(type: 'array')]
    private $preferences = [];

    #[ORM\Column(type: 'datetime')]
    private $register_at;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Reviews::class)]
    private $reviews;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Post::class)]
    private $posts;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comments::class)]
    private $comments;

    #[ORM\Column(type: 'date')]
    private $birthday;

    #[ORM\Column(type: 'object')]
    private $profile_picture;

    #[ORM\ManyToMany(targetEntity: Post::class, mappedBy: 'favorites')]
    private $favposts;

    #[ORM\ManyToMany(targetEntity: self::class, mappedBy: 'abonnes')]
    #[ORM\JoinTable(name: "user_user")]
	#[ORM\JoinColumn(name: "user_source", referencedColumnName: "id")]
	#[ORM\InverseJoinColumn(name: "user_target", referencedColumnName: "id")]
    private $abonnes;

    #[ORM\ManyToMany(targetEntity: self::class, inversedBy: 'abonnements')]
    private $abonnements;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->favorites = new ArrayCollection();
        $this->favposts = new ArrayCollection();
        $this->abonnes = new ArrayCollection();    
        $this->abonnements = new ArrayCollection();    
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified)
    {
        $this->isVerified = $isVerified;

    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }


    public function getPreferences(): ?array
    {
        return $this->preferences;
    }

    public function setPreferences(array $preferences): self
    {
        $this->preferences = $preferences;

        return $this;
    }

    public function getRegisterAt(): ?\DateTimeInterface
    {
        return $this->register_at;
    }

    public function setRegisterAt(\DateTimeInterface $register_at): self
    {
        $this->register_at = $register_at;

        return $this;
    }

    /**
     * @return Collection|Reviews[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Reviews $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Reviews $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setUser($this);
        }

        return $this;
    }
    
    
    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getUser() === $this) {
                $post->setUser(null);
            }
        }

        return $this;
    }

    
    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getProfilePicture()
    {
        return $this->profile_picture;
    }

    public function setProfilePicture($profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    /**
     * @return Collection|Post[]
     * $this->getUser()->getFavposts() // $post->getTitle()
     */
    public function getFavposts(): Collection
    {
        return $this->favposts;
    }

    public function addFavpost(Post $favpost): self
    {
        if (!$this->favposts->contains($favpost)) {
            $this->favposts[] = $favpost;
            $favpost->addFavorite($this);
        }

        return $this;
    }

    public function removeFavpost(Post $favpost): self
    {
        if ($this->favposts->removeElement($favpost)) {
            $favpost->removeFavorite($this);
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getAbonnes(): Collection
    {
        return $this->abonnes;
    }

    public function addAbonne(self $abonne): self
    {
        if (!$this->abonnes->contains($abonne)) {
            $this->abonnes[] = $abonne;
        }

        return $this;
    }

    public function removeAbonne(self $abonne): self
    {
        $this->abonnes->removeElement($abonne);

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getAbonnements(): Collection
    {
        return $this->abonnements;
    }

    public function addAbonnement(self $abonnement): self
    {
        if (!$this->abonnements->contains($abonnement)) {
            $this->abonnements[] = $abonnement;
        }

        return $this;
    }

    public function removeAbonnement(self $abonnement): self
    {
        $this->abonnements->removeElement($abonnement);

        return $this;
    }
}

templates/user/account.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/user/account.css')}}">
{% endblock %}

{% block title %}Mon compte{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row position-relative">
        <a href="{{ path('user_edit')}}">
            <button class="modifyInfos btn btn-primary">Modifier mes informations</button>
        </a>
        <a href="{{ path('user_profile', {id : app.user.id})}}">
            <button class="myProfile btn btn-primary">Accéder à mon profil public</button>
        </a>
        <div class="left col-3">
            <img src="{{ asset( 'uploads/profilePicture/'~ user.profilePicture) }}" alt="profile-pic" class="profile-picture"/>
            {% if role == 'Admin' %}
                <p class="admin">{{ role }}</p>
            {% else %}
                <p class="user">{{ role }}</p>
            {% endif %}
            <h2 class="username">{{ user.username }}</h2>
            <div class="follows mt-5 text-center">
                <p data-bs-toggle="modal" data-bs-target="#abonnes"><span class="fs-5 me-1">{{ numberOfAbonnes }}</span> abonnés</p>
                <p data-bs-toggle="modal" data-bs-target="#abonnements"><span class="fs-5 me-1">{{ numberOfAbonnements }}</span> abonnements</p>
                <p data-bs-toggle="modal" data-bs-target="#favposts"><span class="fs-5 me-1">{{ numberFavposts }}</span> films favoris</p>
            </div>

            <!-- Modals -------------------------->
            
            <!-- Abonnés -->
            <div class="modal fade" id="abonnes" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title fs-3" id="exampleModalLabel">Abonnés</h5>
                    </div>
                    <div class="modal-body fs-5">
                        {% if abonnes is empty %}
                            <p>Aucun abonné</p>
                        {% else %}
                            {% for abonne in abonnes %}
                            <p class="modalAbonnement">
                                <a href="{{ path('user_profile', {'id':abonne.id}) }}" class="text-decoration-none">
                                    <img src="{{ asset('uploads/profilePicture/'~ abonne.profilePicture) }}" alt="Photo de profil" class="profilePicture">{{ abonne.username }}
                                </a>
                            </p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="close btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                    </div>
                </div>
                </div>
            </div>

            <!-- Abonnements -->
            <div class="modal fade" id="abonnements" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title fs-3" id="exampleModalLabel">Abonnements</h5>
                    </div>
                    <div class="modal-body fs-5">
                        {% if abonnements is empty %}
                            <p>Aucun abonnement</p>
                        {% else %}
                            {% for abonnement in abonnements %}
                                <p class="modalAbonnement">
                                    <a href="{{ path('user_profile', {'id':abonnement.id}) }}" class="text-decoration-none">
                                        <img src="{{ asset('uploads/profilePicture/'~ abonnement.profilePicture) }}" alt="Photo de profil" class="profilePicture">{{ abonnement.username }}
                                    </a>
                                </p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="close btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                    </div>
                </div>
                </div>
            </div>

            <!-- Films -->
            <div class="modal fade" id="favposts" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content" style="width:500px">
                    <div class="modal-header">
                        <h5 class="modal-title fs-3" id="exampleModalLabel">Films favoris</h5>
                    </div>
                    <div class="modal-body fs-5">
                        {% if favposts is empty %}
                            <p>Aucun films en favoris</p>
                        {% else %}
                            {% for post in favposts %}
                            <p class="modalAbonnement">
                                <a href="{{ path('user_profile', {'id':post.id}) }}" class="text-decoration-none">
                                    <img src="{{ asset('uploads/covers/'~ post.image) }}" alt="Affiche du film" class="modalCover">{{ post.title }}
                                </a>
                            </p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="close btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                    </div>
                </div>
                </div>
            </div>
            <!-- End Modals -------------------------->

        </div>
        <div class="col-8 ms-5">
            <h1 class="title">Mes informations</h1>
            <p class="mt-5 fs-5 mb-4"><span class="fw-bold me-3">Prénom : </span> {{ user.firstname }}</p>
            <p class="fs-5 mb-4"><span class="fw-bold me-3">Nom : </span> {{ user.lastname }}</p>
            <p class="fs-5 mb-4"><span class="fw-bold me-3">Adresse mail : </span> {{ user.email }}</p>
            <p class="fs-5 mb-4"><span class="fw-bold me-3">Genre : </span> {{ user.gender }}</p>
            <p class="fs-5 mb-4"><span class="fw-bold me-3">Date de naissance : </span>{{ user.birthday|date('d/m/Y') }}</p>
            <p class="fs-5 mb-4"><span class="fw-bold me-3">Âge : </span> {{ age }} ans</p>
            <p class="fs-5 mb-4"><span class="fw-bold me-3">Inscrit le : </span>{{ user.registerAt|date('Y/m/d') }} à {{ user.registerAt|date('H:i:s') }}</p>

            <p class="fs-5 mb-4"><span class="fw-bold me-3">Catégorie(s) préférée(s) : </span> 
                {% set i = 1 %}
                {% for preference in preferences %}
                    {% if i != preferences|length %}
                        {{ preference }} /
                    {% else %}
                        {{ preference }}
                    {% endif %}
                    {% set i = i + 1 %}
                {% endfor %}
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mes informations{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/user/edit.css')}}">
{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row position-relative">
        <a href="{{ path('user_profile', {id : app.user.id})}}">
            <button class="backToAccount btn btn-primary">Revenir sur mon compte</button>
        </a>
        <a href="{{ path('user_profile', {id : app.user.id})}}">
            <button class="myProfile btn btn-primary">Accéder à mon profil public</button>
        </a>
        <div class="left col-3">
            <img src="{{ asset( 'uploads/profilePicture/'~ user.profilePicture) }}" alt="profile-pic" class="profile-picture"/>
            
            <h2 class="username">{{ user.username }}</h2>
            
        </div>
        <div class="modify col-8 ms-5">
            <h1 class="title">Modifier mes informations</h1>
            <form method="post" enctype="multipart/form-data">
                <div class="input">
                    <label for="firstname" class="mt-5 me-3 mb-4 fs-5 fw-bold">Prénom :</label>
                    <input type="text" class="fs-5" name="firstname" id="firstname" value="{{ user.firstname }}">
                </div>
                <div class="input">
                    <label for="lastname" class="mt-2 me-3 mb-4 fs-5 fw-bold">Nom :</label>
                    <input type="text" class="fs-5" name="lastname" id="lastname" value="{{ user.lastname }}">
                </div>

                <div class="input">
                    <label for="username" class="mt-2 me-3 mb-4 fs-5 fw-bold">Pseudo :</label>
                    <input type="text" class="fs-5" name="username" id="username" value="{{ user.username }}">
                </div>

                <div class="input">
                    <label for="email" class="mt-2 me-3 mb-4 fs-5 fw-bold">Adresse mail :</label>
                    <input type="text" class="fs-5" name="email" id="email" value="{{ user.email }}">
                </div>

                <div class="input">
                    <label for="gender" class="mt-2 me-3 mb-4 fs-5 fw-bold">Genre :</label>
                    <select name="gender" id="gender" class="fs-5">
                        {% for gender in genders %}
                            <option value="{{ gender }}" {{ (gender == user.gender) ? 'selected' : '' }}>{{ gender }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="input">
                    <label for="birthday" class="mt-2 me-3 mb-4 fs-5 fw-bold">Date de naissance :</label>
                    <input type="date" class="date fs-5" name="birthday" id="birthday" value="{{ user.birthday|date('Y-m-d') }}">
                </div>

                <div class="input">
                    <label for="image" class="mt-2 me-3 mb-4 fs-5 fw-bold">Photo de profil :</label>
                    <input type="file" name="image" id="image" class="fs-6" accept="image/*">
                </div>
                
                <div class="mb-3">
                    <label for="preference" class="mt-2 me-3 mb-4 fs-5 fw-bold">Catégories</label>
                    {% for preference in preferences %}
                    <label>
                        <input type="checkbox" name="preference[]" value="{{preference}}" {{ (preference in user.preferences) ? 'checked' : '' }}> {{ preference }}
                    </label>
                    {% endfor %}
                </div>
                <button class="save_button btn btn-primary mb-3" name="submit" type="submit">Enregistrer les modifications</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/user/list.html.twig
{% extends 'base.html.twig' %}

{% for user in users %}
    <img src="{{ asset( 'uploads/profilePicture/'~ user.profilePicture) }}" alt="profile-pic" class="profile-picture" style="width:100px;">
    {{user.username}}
    {% for preference in user.preferences %}
        {{preference}}
    {% endfor %}
{% endfor %}






{% endblock %}